// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        int    `json:"id"`
	UserID    int    `json:"user_id"`
	PostID    int    `json:"post_id"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
	ParentID  int    `json:"parent_id"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type Mutation struct {
}

type NewPostRequest struct {
	Token    string `json:"token"`
	Title    string `json:"title"`
	Content  string `json:"content"`
	Comments bool   `json:"comments"`
}

type NewPostResponse struct {
	PostID    int    `json:"post_id"`
	CreatedAt string `json:"created_at"`
}

type ProvideAllPostsRequest struct {
	Page int `json:"page"`
}

type ProvideAllPostsResponse struct {
	Posts []*ProvidePostResponse `json:"posts"`
}

type ProvideCommentRequest struct {
	PostID   int `json:"post_id"`
	ParentID int `json:"parent_id"`
}

type ProvideCommentResponse struct {
	Comments []*Comment `json:"comments"`
}

type ProvidePostRequest struct {
	PostID int `json:"post_id"`
}

type ProvidePostResponse struct {
	ID        int    `json:"id"`
	UserID    int    `json:"user_id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
	Comments  bool   `json:"comments"`
}

type Query struct {
}

type RegisterRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	UserID int `json:"user_id"`
}

type SaveCommentRequest struct {
	Token   string `json:"token"`
	PostID  int    `json:"post_id"`
	Content string `json:"content"`
}

type SaveCommentResponse struct {
	ID        int    `json:"id"`
	CreatedAt string `json:"created_at"`
}

type SaveCommentToCommentRequest struct {
	Token    string `json:"token"`
	PostID   int    `json:"post_id"`
	ParentID int    `json:"parent_id"`
	Content  string `json:"content"`
}
