env: "local"
token_ttl: 1h
grpc:
  host: "localhost"
  port: 8080
  timeout: 3s
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  db_name: "postgres"
  ssl_mode: "disable"