env: "local"
token_ttl: 1h
grpc:
  port: 8888
  timeout: 3s
postgres:
  host: "db"
  port: 5432
  user: "postgres"
  password: "postgres"
  db_name: "postgres"
  ssl_mode: "disable"
clients:
  grpc:
    host: ""
    port: "8080"
    retries_count: 5
    timeout: 3s