// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	UserID    int    `json:"user_id"`
	PostID    int    `json:"post_id"`
	CreatedAt string `json:"created_at"`
	CommentID int    `json:"comment_id"`
}

type Mutation struct {
}

type Post struct {
	ID           string `json:"id"`
	Title        string `json:"title"`
	Content      string `json:"content"`
	UserID       int    `json:"user_id"`
	CreatedAt    string `json:"created_at"`
	AllowComment bool   `json:"allow_comment"`
}

type Query struct {
}

type Save struct {
	ID        int    `json:"id"`
	CreatedAt string `json:"created_at"`
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type ProvideAllPostsInput struct {
	Page int `json:"page"`
}

type ProvideCommentInput struct {
	PostID int `json:"post_id"`
}

type ProvidePostInput struct {
	PostID int `json:"post_id"`
}

type SaveCommentInput struct {
	UserID  int    `json:"user_id"`
	PostID  int    `json:"post_id"`
	Content string `json:"content"`
}

type SaveCommentToCommentInput struct {
	UserID    int    `json:"user_id"`
	PostID    int    `json:"post_id"`
	Content   string `json:"content"`
	CommentID int    `json:"comment_id"`
}

type SavePostInput struct {
	UserID   int    `json:"user_id"`
	Title    string `json:"title"`
	Content  string `json:"content"`
	Comments bool   `json:"comments"`
}

type UserByEmailInput struct {
	Email string `json:"email"`
}

type UserByIDInput struct {
	ID int `json:"id"`
}

type UserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
